site_name: NexGraph Python Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - NexGraph Python Docs: index.md
  - tutorials.md
  #- How-To Guides: how-to-guides.md
  - reference.md
  #- explanations.md

